use std::error::Error;

pub fn main() -> Result<(), Box<Error>> {

    Ok(())
}
